### ISSUE TITLE
Unable to activate spell-checking 

### ISSUE THREAD

**Issue by fdesbiens** [gottcode/focuswriter#129]
Hi.

First, thanks a lot for the great product. I have an issue and I hope you will be able to assist me.

I use the English version of FocusWriter on Windows 8 Pro (64-bit). I downloaded both the French and US-English dictionaries from the LibreOffice site. When I try to add a dictionary, it seems to work at first. The language shows up in the drop down and files are unpacked in C:\Users\<my_account>\AppData\Local\GottCode\FocusWriter\Dictionaries. However, when I close the preferences dialog, spell checking doesn't work. If I reopen the preferences dialog, the newly added language is gone from the drop down. 

My account name contains accentuated characters; maybe this causes the issue? 

Let me know if you need additional information in order to diagnose the problem. Or maybe I just do things the wrong way...

Best Regards,

Frédéric Desbiens.

**Comment by gottcode** [comment]
Fixed in 1.5.0.
