### ISSUE TITLE
Feature request: show "FocusWriter" in window title (optionally?)

### ISSUE THREAD

**Issue by fcFn** [gottcode/focuswriter#153]
After updating to 1.5.3 from 1.4.6 there is no longer "- FocusWriter" label in the window title (so it's file name only). This messes my AutoHotkey script for FocusWriter that relies on window title. 

Is it possible to return the title to previous state i. e. "README.txt - FocusWriter"? Maybe through some kind of semi-hidden options or misc ini file?

**Comment by gottcode** [comment]
The loss the program name from the window title was an unintended side effect of switching to Qt 5, and has been fixed in the git repository. The program title will be shown again in the next feature release.
