### ISSUE TITLE
Apostrophe and smart quotes

### ISSUE THREAD

**Issue by fcFn** [gottcode/focuswriter#154]
You can press Ctrl+[single quote] to insert non-converted single quote if you use smart quotes (or use undo). But when you update quotes in whole document (Smart Quotes -> Update Document), those single quotes get converted into smart ones as well. That includes apostrophes in words such as "don't". 

I suggest a change to the smart quotes mechanism, so quotes inserted between two word symbols without any spaces (such as in words with apostrophes) will never convert. 

Since FocusWriter is mostly used for writing texts, I can't see any use for smart quotes inserted between two word symbols.

I use FW 1.5.3 in Win 7 x64.

**Comment by gottcode** [comment]
Um, the correct quote for don't *is* a smart quote. It is incorrect to use the straight quote there.

**Comment by fcFn** [comment]
Yes, you're right. I didn't think about how it's incorrect to use the straight quote as an apostrophe.

But in multilingual setting (such as Russian-English text, since those languages employ different kinds of quotes) this is an issue. Probably would be too complicated to work around this. I will resort to using Find & Replace in such cases. Not a big deal anyway.

Thanks!

**Comment by gottcode** [comment]
You're welcome! Sorry I won't be able to add a feature to help.

**Comment by fcFn** [comment]
I had an idea today. 

There are different style of quotes for different languages (very nice of you to include different schemes for smart quotes!) but there is only one sign for apostrophe in all languages ([**’**] is shared by all Cyrillic and Latin languages). I propose changing the smart quotes algorithm to ignore smart quotes settings in this case and recognize apostrophe as such (i. e. a quote between two letters without spaces). So regional quotes would still apply, but if you enter [**don't**] it will always change to [**don’t**], and not to [**don“t**] as it does if I choose Russian quoting scheme.

**Comment by gottcode** [comment]
Unfortunately, that would require a complete rewrite of the smart quotes code, which I am not thrilled about. The problem is that the smart quotes runs before you finish typing a word, so it wouldn't know that it was between two word characters instead of at the end of a word. By the time you type the "t" in "don't", for instance, it has already seen the straight quote and converted it to whatever you have set for the closing right quote.

However, I would be willing to add a shortcut to the apostrophe symbol in the symbols dialog to allow you to type the typographical apostrophe (**’**) whenever you want. I was thinking perhaps <tt>Ctrl+Alt+'</tt>; you can even set that yourself today before I add it to the next feature release.

**Comment by fcFn** [comment]
Yeah, I looked at the code (thinking maybe I can implement my suggestion myself) and saw how smart quotes work. Would be too much work for this rather trivial thing.

Shortcut for the typographical apostrophe is a good idea. However here's some considerations:

```Ctrl+Alt+'``` would probably only work in English Layout, since Russian layout doesn't have single quote key mapped (some tradeoffs were made for its 33 letters: physical ```'``` key in Russian is mapped to ```э```; but secondary quotes are used rarely enough, so switching to English and back to enter a single quote a few times isn't that hard). This could be the case for other languages, too. The best solution for all would be too make it a custom shortcut which can be mapped to whatever key combination the user wants. 

If custom shortcut is impossible, I don't think I should set the standard in this case as I use non-standard Russian layout. For those who use both Russian and English standard Win layouts (they're likely to be identical in any OS) ```Ctrl+Alt+=``` should be OK, because the ```=``` key produces the same symbols in both Russian and English standard layouts (the same *probably* is true for other languages). AFAIU, it's a bad idea to use scancode-based shortcuts in cross-platform apps, so multiple layouts have to be taken into consideration.

Also, ```Ctrl+Alt``` is mapped to ```AltGr``` in Win, so in some layouts it will produces unusual symbols. Which one depends on the layout. This behavior could probably be overridden on application level.

As for me, I just discovered that my non-standard English (specifically [Norman layout] (https://www.normanlayout.info)) produces the typographical apostrophe if I press ```Ctrl+Alt+0```. So I used [AHK] (http://ahkscript.org/) to map the same physical key combination to work in my Russian layout. I could also use MKLC (Windows layout creator) to modify my layouts for using ```Ctrl+Alt/AltGr+<some other key>``` to insert an apostrophe (or even just map it to a single key). Those solutions, however, require Windows, some work and/or proper user rights to implement, so they're not for everyone.

**Comment by gottcode** [comment]
Users can override the default shortcuts in the symbols dialog already, so whatever I chose doesn't have to necessarily work for everyone. I would like to support the largest amount possible with the default, of course. Would ```Ctrl+Shift``` be safer than ```Ctrl+Alt``` in Windows? That is already used in several default shortcuts as it is. What about ```Ctrl+Shift+=``` as the default shortcut?

**Comment by fcFn** [comment]
Seems good enough.
