### ISSUE TITLE
Feature - Backup copies on each save

### ISSUE THREAD

**Issue by noximo** [gottcode/focuswriter#155]
Would it be possible to save file in two separate locations during each save? First one would be same as it is now, second one would be a copy of the file with timestamp in a filename in entirely different location.  For example original would be 'C:/books/bestBookEver.txt' and duplicate would be 'D:/backup/books/2015-02-22-11-44-23-bestBookEver.txt' (I would use it for two different cloud storage disks).
In addition to backups it would provide simple revision system.

**Comment by gottcode** [comment]
Up to five backup copies are already saved in the emergency file cache, although I have not yet added any way to access them through the GUI. I have always felt it would be to use a proper external backup solution and revision system than to add a half-formed simplistic option. Sorry.

**Comment by noximo** [comment]
Thanks for your answer. In that case would it be possible to add option to run custom console command on each save? That way it would be easy to replicate behavior I've been asking for and even better - it would be possible to automaticly commit saved file using git on each save.

**Comment by gottcode** [comment]
I will consider it, but I probably won't add it. I have to balance how much each feature costs to add with how many users it would be useful for. And if it fits the vision of the program. Sorry.
