### ISSUE TITLE
BUG: change layout direction when copy and paste

### ISSUE THREAD

**Issue by amirHHP** [gottcode/focuswriter#158]
When you write in RTL mode if copy and paste everything, mode change to LTR automatically.

**Comment by gottcode** [comment]
Unfortunately, I can't recreate this bug. It keeps RTL mode when when I copy and paste, even if I paste into a brand new document. I need more information.

Are you pasting into a new document in FocusWriter, or into a different program? What operating system are you using? And finally, what version of FocusWriter are you using?

**Comment by amirHHP** [comment]
I use FocusWriter 1.4.5 on Linux Mint 17.1 (also I tested on OpenSuse Gnome 13.1 and Opensuse KDE 12.3) I pasting in FocusWriter not another program.
For example in this image I have a text in Persian (Farsi) language in RTL direction. 
![screenshot from 2015-04-05 16 44 15](https://cloud.githubusercontent.com/assets/5258360/6996784/14aef1bc-dbb3-11e4-9381-27b543ed3231.png)
When I copy and paste (with Ctrl+C and Ctrl+V OR menu) text direction change like this:
![screenshot from 2015-04-05 16 46 52](https://cloud.githubusercontent.com/assets/5258360/6996789/68cb73ec-dbb3-11e4-9652-563662aa80b3.png)
dots move right and when I press left button cursor move right and when press right cursor move left and end line define in right not left. in format menu, direction change to LTR.

**Comment by gottcode** [comment]
I see. Unfortunately, that is an old and unsupported version of FocusWriter. Would you be willing to test the current release branch from my [PPA](https://launchpad.net/~gottcode/+archive/ubuntu/gcppa)?

**Comment by amirHHP** [comment]
Thanks, new version there isn't this bug but I found a new bug about Zero-width non-joiner in this version there isn't Zero-width non-joiner that use in Persian, Hebrew and german.

**Comment by gottcode** [comment]
Unfortunately, this is a bug in Qt (https://bugreports.qt.io/browse/QTBUG-42074), and not something I can do anything about. In the future, please open a new bug report for each issue. Thanks!
