### ISSUE TITLE
Feature: Add Image Support (bullet support reiteration)

### ISSUE THREAD

**Issue by catwizard69** [gottcode/focuswriter#160]
It would be great if we could insert images.

I'd also like to reiterate that bullet support would be extremely useful. I've found a work-around by adding hotkeys for bullet points and taking advantage of the increase indention size, but it'd be much more convenient to implement this like traditional word processors do.

**Comment by gottcode** [comment]
I'm sorry, but I am completely opposed to adding image support to FocusWriter.

Also, I am already considering adding list support, but I make no promises. I would appreciate it if you would stay to a single topic for each GitHub issue.
