### ISSUE TITLE
Cannot read character under block insertion cursor

### ISSUE THREAD

**Issue by bugreport1** [gottcode/focuswriter#162]
The block insertion cursor is the same color as the text.
When hovering over a character, this turns it into a solid block of color.
 
The character that the block is over should be changed to the Text Background color to prevent this from happening.

**Comment by gottcode** [comment]
Sorry, the block cursor is handled by Qt, not FocusWriter. You wouldn't see the character no matter what color it is, because the block cursor is drawn *over* the character.
