### ISSUE TITLE
Feature Request: Change font size.

### ISSUE THREAD

**Issue by GhostSquad57** [gottcode/focuswriter#165]
I think being able to change the font size for selected text would be an excellent feature for Focuswriter.

I understand that it's possible to change the font size via the Themes menu, but this affects *all* the text inside the document; and I like to use different font sizes for headers, titles, etc.

On Libreoffice Writer, font size can be changed on-the-fly with `Ctrl+[` and `Ctrl+]`

**Comment by gottcode** [comment]
I'm sorry, but I am against arbitrary font size selection in FocusWriter. It would conflict with the theme font sizes. I have added headings to the git version, and those have larger fonts (scaled up by each heading, so heading 2 is smaller than heading 1, etc).
