### ISSUE TITLE
Feature Request: custom FW file extension

### ISSUE THREAD

**Issue by alloween** [gottcode/focuswriter#166]
I save my creative writing exclusively as .txt files (I don't like formatting to get in the way of my initial work flow). But there are many other .txt files I open on a daily basis which have nothing to do with my creative work and I only want to open using Notepad.

I have gone back and forth between choosing the default program for opening .txt files (one week it's FW, the next it's Notepad, then it's back to FW, etc.), but always end up having to right click and choose the 'open with' feature in the context menu dozens of times a day, no matter what - which gets very annoying after a while.

Recently I have been renaming every .txt I am currently working on in FocusWriter as .tfw just to make my life easier. But even this process is laborious (considering I still have hundreds of .txt files of creative writing which I have yet to change the extension for - although I guess I could use a renamer to run a batch extension change).

What I am proposing is an option to have a custom file extension used, which FocusWriter will be set as the default program to open, and will be recognized as a .txt, .rtf, .odt, or whatever file format people prefer to save their work in when being opened by FW. This could be implemented in the 'save as' dialogue as a tick box.

**Comment by gottcode** [comment]
I'm sorry, I will not be adding this feature to FocusWriter.
