### ISSUE TITLE
Corrupted file

### ISSUE THREAD

**Issue by bodhin** [gottcode/focuswriter#170]
Somehow Focuswriter corrupted my file (.odt). When opening the file, I get the following message: Unexpected ".

If I try to open the file with LibreOffice, it tells me there is a problem with the file and the coordinates (line, column). When I unzip the .odt and open content.xml with a text editor, in those coordinates there is a character that my editor shows as ^@ (isn't that ASCII 0?) If I remove that character and zip it all back to .odt again, Focuswriter does not open the file but LibreOffice tells me its corrupted but is able to fix it.

I was able to download earlier versions of this file from Dropbox. I'm now able to reconstruct my file by hand but if you want to debug this, I can send you the files by e-mail.

**Comment by bodhin** [comment]
I'm using Ubuntu 15.04.

**Comment by gottcode** [comment]
> I was able to download earlier versions of this file from Dropbox. I'm now able to reconstruct my file by hand but if you want to debug this, I can send you the files by e-mail.

I would like to try to fix this, so please email me the files. I don't know if I will be able to figure out what happened, but I would like to try. I'm glad to hear that you can reconstruct your data!

> If I remove that character and zip it all back to .odt again, Focuswriter does not open the file but LibreOffice tells me its corrupted but is able to fix it.

The reason why just zipping up the files again doesn't work is that ODT files are not just simply Zip files; you have to have the *uncompressed* mimetype file as the first file in the Zip file to signal that it is an ODT document.

**Comment by bodhin** [comment]
I just noticed this bug occurs when I copy text from Chrome. To reproduce:

1. Open new document in Focuswriter.
2. Open a site in Chrome. Copy some text.
3. Paste into Focuswriter document. Save as .odt.

I copied sentence "Look what’s landing in India" from ubuntu.com and this is what I got:

`  <office:text>`
`   <text:p text:style-name="P1">Look what’s landing in India</text:p>`
`   <text:p text:style-name="P1">^@</text:p>`
`  </office:text>`

**Comment by gottcode** [comment]
Thanks for all of the information! From it I was able to track down what was happening: Qt was not parsing the HTML from Chrome properly and was appending a null character (which is invalid), and then FocusWriter was happily saving it to disk (and therefore creating an invalid document). I have fixed it, and the next release will not create badly formed documents.
