### ISSUE TITLE
newline at end of file

### ISSUE THREAD

**Issue by avdd** [gottcode/focuswriter#171]
Text files should end with a newline character (specifically: each line should end with a newline)

See: http://stackoverflow.com/questions/729692/why-should-files-end-with-a-newline

**Comment by gottcode** [comment]
I disagree. FocusWriter is a word processor, not a text editor, and the files it creates are *not* required to be POSIX-compliant text files. FocusWriter is first and foremost about fiction writing. If the user doesn't want a newline at the end of the file, they don't have to have one. It is up to the writer, not the program.
