### ISSUE TITLE
 Unicode ZWNJ does not work

### ISSUE THREAD

**Issue by hosseinn** [gottcode/focuswriter#172]
It is not possible to insert Unicode character ZWNJ (https://en.wikipedia.org/wiki/Zero-width_non-joiner) in the text. This is the bug from the upstream Qt 5:
https://bugreports.qt.io/browse/QTBUG-42074

Any workarounds?

**Comment by gottcode** [comment]
Well, the only workaround I can think of is to open up the symbols dialog and find the ZWNJ character under the "General Punctuation" block. Add a keyboard shortcut for it (I tested with Ctrl+Space), and then you can insert it with whatever keyboard shortcut you set. It works for me with Arch Linux and English input.
