### ISSUE TITLE
Justify text doesn't work on Linux

### ISSUE THREAD

**Issue by hpetrus** [gottcode/focuswriter#174]
Versions 1.4.x to present have had this bug.  Text will not justify to margins.  This is true, whether you select existing text with alignment and justify it, or when starting a whole new document with justification turned on.

**Comment by gottcode** [comment]
What versions have you tested? What Linux are you using? And what version of Qt are you using? This bug does not happen for me in any of my test environments.

**Comment by hpetrus** [comment]
Linux Mint 17.2 KDE edition.  Version of Qt I'm not sure about because I'm not at that workstation.  What Qt should I be using?

**Comment by gottcode** [comment]
How are you installing FocusWriter for Linux Mint? I don't provide packages for it. Are you compiling it yourself? Or are you using the Ubuntu packages? The Ubuntu packages depend on Qt 5. The version of FocusWriter included with Linux Mint, version 1.4.5, depends on Qt 4, and does not exhibit this bug for me.

When I build FocusWriter from source using Qt 4.8 in Mint, this bug does not happen. When I build it with Qt 5.2, this bug happens. It is a bug in Qt 5.2, not FocusWriter. You should be able to use FocusWriter 1.4.5 from Linux Mint without issues. Or you could compile FocusWriter from source against Qt 4.
