### ISSUE TITLE
Ctrl-S to save produces an 's' if already saved

### ISSUE THREAD

**Issue by hpetrus** [gottcode/focuswriter#175]
On Linux, Ctrl+S will type an 's' on screen, if there are no new changed to save.  After the 's' appears, there is, of course, a change, so the next Ctrl+S will save changes.  This has been the case since V1.4.x to present.

The Mac version doesn't suffer from this problem any longer.

**Comment by gottcode** [comment]
What versions have you tested? What Linux are you using? And what version of Qt are you using? This bug does not happen for me in any of my test environments.

**Comment by hpetrus** [comment]
I'm using Linux Mint 17.2 KDE edition.  The versions I've tested are from 1.4.x to the current 1.5.5.  Qt, I'm not sure on because I'm not at the workstation, at the moment.  What do you recommend?

**Comment by gottcode** [comment]
How are you installing FocusWriter for Linux Mint? I don't provide packages for it. Are you compiling it yourself? Or are you using the Ubuntu packages? The Ubuntu packages depend on Qt 5. The version of FocusWriter included with Linux Mint, version 1.4.5, depends on Qt 4, and does not exhibit this bug for me.

When I build FocusWriter from source using Qt 4.8 in Mint, this bug does not happen. When I build it with Qt 5.2, this bug happens. It is a bug in Qt 5.2, not FocusWriter. You should be able to use FocusWriter 1.4.5 from Linux Mint without issues. Or you could compile FocusWriter from source against Qt 4.

**Comment by hpetrus** [comment]
I'm installing it from your repo, I believe.  I don't use the version included in Mint's repos because it's old.

If there aren't major issues with building against Qt 4.8, then I'll do that.  Are there any pitfalls to doing this?  Also, are all your builds on your repo built for Qt 5 for the current version of FocusWriter?

**Comment by gottcode** [comment]
There should be no problems building against Qt 4.8, and I didn't encounter any when I did a quick test earlier. I don't use Qt 4 anymore, though, and I don't provide any builds for it. And once I release 1.6 I will be dropping support for Qt 4 entirely, sorry.

**Comment by hpetrus** [comment]
There's no point in me using Qt 4.x, anymore, then.  I'll just live with 
the bug in Qt 5.2.  Maybe the next point release of 5 will have this 
fixed.  I'll take a look at the source code and see if I can trace 
what's going on between it and Qt 5.2 and go from there.  Any hints 
before I do this?

I love this programme too much to be left behind.  I use it every day.  
Thank you, very much for it.

**Comment by gottcode** [comment]
The version of Qt 5 in Linux Mint is quite old, actually. The bug was fixed in Qt 5.3, and the current version is 5.5. I'm not sure which commit fixed things, but I do remember that this bug was fixed in Qt 5.3 (which is how this issue was solved for the Mac: I just used a newer Qt).

I'm glad you enjoy FocusWriter so much, and I'm sorry that the version of Qt in Linux Mint is causing you issues.

**Comment by hpetrus** [comment]
Usually, Qt can coexist on systems with previous or other versions of 
Qt, like Qt 4.8.  Before I download the latest Qt 5.5 from qt.io, are 
there any pitfalls I should look out for that you might be aware of?

Thanks, for your input, Graeme.

**Comment by gottcode** [comment]
Not that I'm aware of. It should be pretty easy to install in a directory other than /usr, and then use the qmake built from that to build FocusWriter.

**Comment by hpetrus** [comment]
Thank you.

Onwards, then.
