### ISSUE TITLE
Focus Writer Writing View

### ISSUE THREAD

**Issue by fotodok** [gottcode/focuswriter#176]
I'm a long time Mac user who enjoyed writing with IA Writer. I've recently moved to a Surface Pro 3 with a high resolution screen. When I found that IA Writer was not available for Windows I also saw Focuswriter described as an IA Writer-like application, so I purchased it. I'm disappointed by the GUI implementation as it is rendered on a high resolution screen.

First, the included themes are odd. All I want is a white background with black text as though I was typing on paper. For a new user to have to learn how to create a custom theme just to have black text on a white background seems unreasonable.

Second, the size of the default text on a current generation, high resolution screen is tiny, yet I see no mechanism to adjust text size. I'd also want to be able to type with a 1.5 or 2 line spacing for preparing manuscripts though if I can't change text size I suspect I can't adjust this either.

Third, the width of the virtual page, as rendered on the Surface Pro 3 screen is crazy narrow. It seems to only use about 1/4 of the screen width. The effect is like taking an 8.5x11 piece of paper and only typing in the middle two inches of the paper.

Perhaps it's my unfamiliarity with the program but I think for a supposedly simple, minimalist approach to writing, like IA Writer, the default workspace leaves much to be desired. Hopefully I'll hear from the developer and discover there are easy answers to these short comings.

**Comment by gottcode** [comment]
> First, the included themes are odd. All I want is a white background with black text as though I was typing on paper. For a new user to have to learn how to create a custom theme just to have black text on a white background seems unreasonable.

The whole point of FocusWriter is to custome the writing environment. Theming is a big part of why I created FocusWriter at all! However, I will consider adding just a blank, plain theme.

> Second, the size of the default text on a current generation, high resolution screen is tiny, yet I see no mechanism to adjust text size. I'd also want to be able to type with a 1.5 or 2 line spacing for preparing manuscripts though if I can't change text size I suspect I can't adjust this either.

The font and its size are set in the theme, not in the document. The line spacing is also set in theme.

> Third, the width of the virtual page, as rendered on the Surface Pro 3 screen is crazy narrow. It seems to only use about 1/4 of the screen width. The effect is like taking an 8.5x11 piece of paper and only typing in the middle two inches of the paper.

The width of the page is, again, set in the theme. The reason you are having such difficulties with the size being so small is that FocusWriter does not yet have native support for high resolution displays, and it won't for a while. Sorry.
